# Generated by Django 4.2.9 on 2024-06-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Mobile',
            new_name='mobile',
        ),
    ]
