# Generated by Django 4.2.9 on 2024-06-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_mobile_customer_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='empid',
            new_name='cSid',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='1', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
