# Generated by Django 4.2.9 on 2024-06-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_empid_customer_csid_customer_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='category',
            new_name='CategoryName',
        ),
    ]
