# Generated by Django 4.2.9 on 2024-06-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_category_recipe_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='recipe',
            new_name='RecipeId',
        ),
    ]
