# Generated by Django 4.2.9 on 2024-06-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_recipe_rating_recipeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='recipe',
            new_name='RecipeId',
        ),
    ]
